language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-joomla-admin-template' ]; then cd .. && eval "mv $currentfolder generator-joomla-admin-template" && cd generator-joomla-admin-template; fi

